# Generated by Django 3.2.8 on 2022-08-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='politically_exposed_person',
        ),
    ]
