# Generated by Django 3.2.8 on 2022-08-25 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateField(default=datetime.datetime)),
                ('updated_on', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departments',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
            },
        ),
    ]
