# Generated by Django 3.2.8 on 2022-08-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='departments',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
