# Generated by Django 3.2.8 on 2022-08-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_auto_20220826_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='updated_on',
        ),
    ]
