# Generated by Django 3.2.8 on 2022-08-25 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_auto_20220826_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('doctor_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('flag_status', models.CharField(max_length=1)),
                ('mobileno', models.IntegerField()),
                ('report_mail_flag', models.CharField(max_length=1)),
                ('report_login_id', models.CharField(max_length=100)),
                ('report_password', models.CharField(max_length=100)),
                ('int_code', models.CharField(max_length=100)),
                ('last_modified_on', models.DateField()),
                ('dob', models.DateField()),
                ('anniversary_date', models.DateField()),
                ('license_no', models.CharField(max_length=200)),
                ('pro_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctor',
                'db_table': 'Doctor',
            },
        ),
    ]
