# Generated by Django 3.2.8 on 2022-08-26 05:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=250)),
                ('short_dep_name', models.CharField(max_length=20, null=True)),
                ('code', models.IntegerField(null=True)),
                ('barcode_print_flag', models.BooleanField(default=True)),
                ('email_flag', models.BooleanField(default=True)),
                ('sms_flag', models.BooleanField(default=True)),
                ('departments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.departments')),
            ],
            options={
                'verbose_name': 'Sub Departments',
                'verbose_name_plural': 'Sub Departments',
                'db_table': 'sub_departments',
            },
        ),
    ]
