# Generated by Django 3.2.8 on 2022-08-27 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_subdepartments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=250, null=True)),
                ('report_name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('method', models.CharField(max_length=30)),
                ('suffix', models.CharField(max_length=2)),
                ('formulae', models.CharField(max_length=100)),
                ('dc', models.CharField(max_length=1)),
                ('precision', models.IntegerField()),
                ('default_status', models.CharField(max_length=1)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parameters',
                'verbose_name_plural': 'Parameters',
                'db_table': 'parameters',
            },
        ),
    ]
