# Generated by Django 3.2.8 on 2022-08-27 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sampletype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('sample_type', models.CharField(choices=[('A', 'Register'), ('B', 'Sample Collect'), ('C', 'Sample Accept')], default='A', max_length=1, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sampletype',
                'verbose_name_plural': 'Sampletype',
                'db_table': 'sampletype',
            },
        ),
    ]
