# Generated by Django 3.2.8 on 2022-09-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='disporder',
        ),
        migrations.AddField(
            model_name='titles',
            name='dislay_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
