# Generated by Django 3.2.8 on 2022-09-19 04:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_auto_20220901_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=250, null=True)),
                ('report_name', models.CharField(max_length=100, unique=True)),
                ('services_map_code', models.CharField(max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('method', models.CharField(max_length=30)),
                ('service_order', models.IntegerField()),
                ('report_format', models.IntegerField()),
                ('is_suppress_report_name', models.BooleanField(default=True)),
                ('service_footer', models.CharField(max_length=250, null=True)),
                ('is_outside', models.BooleanField(default=True)),
                ('is_print_together', models.BooleanField(default=True)),
                ('is_web_flag', models.BooleanField(default=True)),
                ('services_alias', models.CharField(max_length=30)),
                ('services_days', models.IntegerField()),
                ('is_critical_flag', models.BooleanField(default=True)),
                ('is_sms_flag', models.BooleanField(default=True)),
                ('color_code', models.CharField(max_length=30)),
                ('disposal_day', models.IntegerField()),
                ('gender_type', models.CharField(max_length=6)),
                ('special_instruction', models.CharField(max_length=250, null=True)),
                ('pat_instruction', models.CharField(max_length=250, null=True)),
                ('tech_instruction', models.CharField(max_length=250, null=True)),
                ('is_question_flag', models.BooleanField(default=True)),
                ('is_urgent_flag', models.BooleanField(default=True)),
                ('lab_process_time', models.IntegerField()),
                ('urgent_process_time', models.IntegerField()),
                ('is_consent_flag', models.BooleanField(default=True)),
                ('services_status', models.CharField(max_length=1)),
                ('is_services_for_home_collection', models.BooleanField(default=True)),
                ('is_pdf_services', models.BooleanField(default=True)),
                ('is_manual_services', models.BooleanField(default=True)),
                ('is_gst_services', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sample_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.sampletype')),
                ('service_deptname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.subdepartments')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'service',
                'db_table': 'service',
            },
        ),
    ]
