# Generated by Django 3.2.8 on 2022-10-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0010_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='full_name',
        ),
    ]
