# Generated by Django 3.2.8 on 2022-10-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0011_rename_doctor_name_doctor_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='last_modified_on',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='mobileno',
        ),
    ]
