# Generated by Django 3.2.8 on 2022-10-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0012_auto_20221007_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='dislay_order',
            new_name='display_order',
        ),
    ]
