# Generated by Django 3.2.8 on 2022-11-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='m', max_length=1, unique=True)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('patient_type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('nationality', models.IntegerField()),
                ('passport_no', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=100)),
                ('last_visit_date', models.DateField(null=True)),
            ],
        ),
    ]
