# Generated by Django 3.2.8 on 2022-11-01 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0014_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_no', models.CharField(max_length=100)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_rate', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('other_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('receipt_no', models.CharField(max_length=100)),
                ('complete_flag', models.BooleanField(default=False)),
                ('ref_number', models.CharField(max_length=255)),
                ('dispatch_mode', models.CharField(max_length=1)),
                ('invalid_flag', models.IntegerField()),
                ('consumable_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('visit_time', models.TimeField()),
                ('bill_number', models.IntegerField()),
                ('age_in_days', models.IntegerField()),
                ('registration_code', models.IntegerField()),
                ('sms_repost', models.BooleanField(default=False)),
                ('web_repost', models.BooleanField(default=False)),
                ('hard_copy_repost', models.BooleanField(default=False)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.doctor')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.patient')),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.source')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
